import React from 'react'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next Library - Books',
  description: 'Generated by create next app',
}

const BooksLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return <div>{children}</div>
}

export default BooksLayout
