import React from 'react'
import { Metadata } from 'next'
import InfoBar from '@/app/me/components/InfoBar/InfoBar'

export const metadata: Metadata = {
  title: 'Next Library - Home',
  description: 'Generated by create next app',
}

const HomeLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <div>
      <InfoBar />
      {children}
    </div>
  )
}

export default HomeLayout
