import React from 'react'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next Library - Home',
  description: 'Generated by create next app',
}

const HomeLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return <div>{children}</div>
}

export default HomeLayout
